package:
  name: xray
  version: "0.4.0"

source:
  fn: xray-0.4.0.tar.gz
  url: https://pypi.python.org/packages/source/x/xray/xray-0.4.0.tar.gz
  md5: 0950272844f6acf4963bd9acba1e25e6

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas >=0.15

  run:
    - python
    - numpy
    - pandas >=0.15

test:
  imports:
    - xray
    - xray.backends

  requires:
    - nose

  commands:
    - nosetests xray

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'N-D labeled arrays and datasets in Python'
