package:
  name: xray
  version: "0.3.1"

source:
  fn: xray-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/x/xray/xray-0.3.1.tar.gz
  md5: 148c7b2e6c757373025d541833742003

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas >=0.13.1

  run:
    - python
    - numpy
    - pandas >=0.13.1

test:
  imports:
    - xray
    - xray.backends

  requires:
    - nose

  commands:
    - nosetests xray

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'N-D labeled arrays and datasets in Python'
