package:
  name: xray
  version: "v0.2.0alpha_4_g6c394b1"

source:
  fn: xray-6c394b14ecc04a53d804893060ed33cadfde688e.tar.gz
  url: https://github.com/xray/xray/archive/6c394b14ecc04a53d804893060ed33cadfde688e.tar.gz
  sha1: 9b50e44bf4a9015aea51efc18e3c6ad1da1c0990
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - xray = xray:main
    #
    # Would create an entry point called xray that calls xray.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas >=0.13.1

  run:
    - python
    - numpy
    - pandas >=0.13.1

test:
  # Python imports
  imports:
    - xray
    - xray.backends

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'Extended arrays for working with scientific datasets in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
