package:
  name: xray
  version: "0.3.2"

source:
  fn: xray-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/x/xray/xray-0.3.2.tar.gz
  md5: 332c9112edb4e3056aa091fbc4f8f120

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas >=0.15

  run:
    - python
    - numpy
    - pandas >=0.15

test:
  imports:
    - xray
    - xray.backends

  requires:
    - nose

  commands:
    - nosetests xray

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'N-D labeled arrays and datasets in Python'
