package:
  name: xray
  version: "0.3.0"

source:
  fn: xray-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/x/xray/xray-0.3.0.tar.gz
  md5: e68f13bec0e6efaf4b8db8cf06889dbe

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas >=0.13.1

  run:
    - python
    - numpy
    - pandas >=0.13.1

test:
  imports:
    - xray
    - xray.backends

  requires:
    - nose

  commands:
    - nosetests xray

about:
  home: https://github.com/xray/xray
  license: Apache Software License
  summary: 'N-D labeled arrays and datasets in Python'
